replicaCount: 1
ingress:
  enabled: true
  tls:
    enabled: true
    secretName: "kube-cert"
service:
  externalPort: 80
  internalPort: 80
livenessProbe:
  initialDelaySeconds: 100
readinessProbe:
  initialDelaySeconds: 80


